# Generated by Django 4.2 on 2023-04-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleaos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=20)),
                ('PrimerApellido', models.CharField(max_length=20)),
                ('OtrosNombres', models.CharField(max_length=50)),
                ('PaisEmpleo', models.CharField(max_length=15)),
                ('Correo', models.CharField(max_length=300)),
            ],
        ),
    ]
